apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-pruebas-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-pruebas
  template:
    metadata:
      labels:
        app: jenkins-pruebas
    spec:
      containers:
      - name: jenkins-pruebas
        image: iad.ocir.io/idxyojfomq6q/jenkins_pruebas:${BUILD_NUMBER}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
      imagePullSecrets:
      - name: oci-registry-secret
